global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'linux-monitoring'
    static_configs:
      - targets: ['web:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
